In [6]:
import numpy as np

In [ ]:
### Import the IDs list as an array, each column correponds to a list of IDs
ID_list_txt = open('ID_list.txt','r')
ID_list = ID_list_txt.read().splitlines()
for i, IDs in enumerate(ID_list) :
    ID_list[i] = IDs.split("   ")
ID_list = np.array(ID_list, dtype=int)
print("IDs list :\n", ID_list)

IDs list :
 [[77442 88154]
 [71181 76363]
 [49755 69158]
 ...
 [69182 95805]
 [59092 67571]
 [29363 98020]]


In [ ]:
### Separate and sort each ID list

# Separate
ID_list_1 = ID_list[:,0]
ID_list_2 = ID_list[:,1]

# Sort
ID_list_1_sorted = np.sort(ID_list_1)
ID_list_2_sorted = np.sort(ID_list_2)

print("Sample of ID list 1 :\n", ID_list_1[:10], "\nSample of sorted ID list 1:\n",ID_list_1_sorted[:10])
print("\nSample of ID list 2 :\n", ID_list_2[:10], "\nSample of sorted ID list 2:\n",ID_list_2_sorted[:10])


Sample of ID list 1 :
 [77442 71181 49755 38798 89857 96168 68503 52053 27070 78107] 
Sample of sorted ID list 1:
 [10066 10149 10186 10193 10468 10479 10730 10741 10780 10872]

Sample of ID list 2 :
 [88154 76363 69158 22488 49242 60034 43760 29173 63754 13305] 
Sample of sorted ID list 2:
 [10232 10468 10468 10468 10468 10468 10468 10468 10468 10468]


In [16]:
### Compute distance between lists
ID_difference_list = abs(ID_list_1_sorted - ID_list_2_sorted)
ID_distance = np.sum(ID_difference_list)

print("Distance between the ID lists : ",ID_distance)

Distance between the ID lists :  2176849


In [19]:
### Part 2 - Compute similarity as defined on the website

# Initialization
ID_occurence_dict = {}  # Dictionnary that memorizes IDs' number occurence in the 2nd list to avoid unnecessary compute
similarity = 0

for ID in ID_list_1 :

    # Compute and memorize ID's number of occurence in the 2nd list if not done yet
    if ID not in ID_occurence_dict.keys():
        ID_check = ID*np.ones(len(ID_list_2))
        ID_occurence = np.sum(ID_list_2 == ID_check)
        ID_occurence_dict[ID] = ID_occurence
    
    else:
        ID_occurence = ID_occurence_dict[ID]
    
    similarity += ID*ID_occurence

print("Similarity between the two lists :", similarity)

Similarity between the two lists : 23384288
